#!/usr/bin/python

# bootstrap -- Bootstrap script for the Rocket engine.
# this script downloads and builds a copy of waf, which is then used by the rest of the build process.

import bz2
import os
import stat
import StringIO
import subprocess
import sys
import tarfile
import urllib2

DEPS_DIR = "deps"
PKGS = {
        "waf": {
            "type": "tarball",
            "url": "http://waf.googlecode.com/files/waf-%(version)s.tar.bz2",
            "version": "1.6.11"
        },
        "lua": {
            "type": "tarball",
            "url": "http://www.lua.org/ftp/lua-%(version)s.tar.gz",
            "version": "5.2.1"
        },
        "sdl2": {
            "type": "hg",
            "url": "http://hg.libsdl.org/SDL",
            "version": "hg"
        },
        "libuv": {
            "type": "git",
            "url": "https://github.com/joyent/libuv.git",
            "version": "git"
        }

}

WAF_BUILD_CMD = ["python", "waf-light"]
WAF_TOOLS = ["compat15", "msvs", "xcode"]

class DependencyBuilder(object):

    def __init__(self, pkg, info):
        self.pkg = pkg
        self.info = info

        if not self.exists():
            getattr(self, "download_%s" % self.info["type"])()

    def pkg_path(self):
        return os.path.join(DEPS_DIR, "%s-%s" % (self.pkg, self.info["version"]))

    def pkg_url(self):
        return self.info["url"] % self.info

    def download_tarball(self):
        print ("downloading tarball for %s" % self.pkg)
        urlObj = urllib2.urlopen(self.pkg_url())
        fileObj = StringIO.StringIO(urlObj.read())
        tarball = tarfile.open(None, "r", fileObj)
        tarball.extractall(self.pkg_path())

    def download_git(self):
        print ("cloning from git for %s" % self.pkg)
        subprocess.call(["git", "clone", self.pkg_url(), self.pkg_path()])

    def download_hg(self):
        print ("cloning from hg for %s" % self.pkg)
        subprocess.call(["hg", "clone", self.pkg_url(), self.pkg_path()])

    def exists(self):
        return os.path.exists(self.pkg_path())

def grab_tarball(dir_path, url):
    urlObj = urllib2.urlopen(url)
    fileObj = StringIO.StringIO(urlObj.read())
    tarball = tarfile.open(None, "r", fileObj)
    tarball.extractall(dir_path)

def build_waf(waf_dir):
    proj_root = os.getcwd()
    os.chdir(os.path.join(proj_root, waf_dir))
    tool_list = "--tools=%s" % (",".join(WAF_TOOLS))
    subprocess.call(WAF_BUILD_CMD + [tool_list])

    # copy the created waf file into the project root
    open(os.path.join(proj_root, "waf"), "wb").write(open("waf", "rb").read())

    # change back to the project root directory
    os.chdir(proj_root)
    os.chmod("waf", stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)


def main():
    if not os.path.exists(DEPS_DIR): os.mkdir(DEPS_DIR)
    for pkg, pkg_info in PKGS.items():
        DependencyBuilder(pkg, pkg_info)
        
    # build the waf package
    if not os.path.exists("waf"):
        print "building waf binary"
        build_waf(os.path.join(DEPS_DIR, "waf-%s" % PKGS["waf"]["version"]))

    # run the 'waf configure command
    subprocess.call(["./waf", "configure"])

if __name__ == "__main__":
    main()

