#!/usr/bin/env python

SRC_DIR = "src"

def options(ctx):
    ctx.load("compiler_c")

def configure(ctx):
    ctx.load("compiler_c")
    ctx.check_cc(lib="m", uselib_store="M")
    ctx.check_cc(lib="readline", uselib_store="RL")


def build(ctx):
    srclst = ctx.path.ant_glob("%s/l*.c" % SRC_DIR, excl=["%s/lua.c" % SRC_DIR, "%s/luac.c" % SRC_DIR])

    luacflags = ["-02", "-Wall", "-DLUA_COMPAT_ALL", "-DLUA_USE_MACOSX"]

    ctx.stlib(
            source = srclst,
            target = "liblua",
            cflags = luacflags,
            name = "static-lua",
            )

    ctx.program(
            source = "%s/lua.c" % SRC_DIR,
            target = "lua",
            cflags = luacflags,
            use = ["static-lua", "M", "RL"],
            )

    ctx.program(
            source = "%s/luac.c" % SRC_DIR,
            target = "luac",
            cflags = luacflags,
            use = ["static-lua", "M", "RL"],
            )


